<?php

namespace AppBundle\Repository;

use AppBundle\Entity\konto;

/**
 * kontoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class kontoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $userId
     * @param $iban
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneByIbanJoinedToUser($userId, $iban)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT k
    FROM AppBundle:konto k, AppBundle:user  u
    WHERE u.id = :userId
    And k.iban = :iban'
            )
            ->setParameter('userId', $userId)
            ->setParameter('iban', $iban);

        return $query->getResult();
    }

    /**
     * @param $kontoId
     * @return array
     */
    public function findTransactionsForKonto($kontoId)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT t
    FROM AppBundle:konto k, AppBundle:transaction t
    WHERE k.id = :kontoId
    AND k.id = t.transactionKonto'
            )
            ->setParameter('kontoId', $kontoId);

        return $query->getResult();
    }
}
