<?php

namespace AppBundle\Repository;

/**
 * paymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paymentRepository extends \Doctrine\ORM\EntityRepository
{
}
