<?php

namespace AppBundle\Repository;

/**
 * transactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class transactionRepository extends \Doctrine\ORM\EntityRepository
{
}
