AppBundle\Entity\user:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\userRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        vorname:
            type: string
            length: 255
        nachname:
            type: string
            length: 255
        geburtstag:
            type: datetime
        benutzername:
            type: string
            length: 255
        passwort:
            type: string
            length: 255
        email:
            type: string
            length: 255
        avatar:
            type: string
            length: 255
    manyToOne:
        role:
            targetEntity: AppBundle\Entity\role
            inversedBy: users
            joinColumn:
                name: roleId
                referencedColumnName: id
    oneToMany:
        kontos:
            targetEntity: AppBundle\Entity\konto
            mappedBy: konto
        addresses:
            targetEntity: AppBundle\Entity\address
            mappedBy: address
        transactions:
            targetEntity: AppBundle\Entity\transaction
            mappedBy: transactionUser
    lifecycleCallbacks: {  }
